layout_spectrum: 0.28452891833148897
typography_spectrum: 0.8614202428143471
color:
  brandStrength: 0.47506067575886846
  lightness: 0.42238880577497184
  saturation: 0.6157707835081965
  rhythmicContrast: 0.4210375847760588
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Luca Nervegna cinematographer
